ADMIN_AUTH_METHOD_NAME=/Admin/admin-api-key
ADMIN_ACCESS_ID=p-6egqnps520x6am
ADMIN_ACCESS_KEY=5lubM4dBKWZw1+QKiXp4i3JJUNp8hpkcw4JrsPgjGTs=

GATEWAY_AUTH_METHOD_NAME=/Gateway/gateway-api-key
GATEWAY_ACCESS_ID=p-3gvkt21rdiutam
GATEWAY_ACCESS_KEY=PG4Meb284BCmePTRfyty6XwHBwPH0yXBVSftr9brTVo=
