# --- Gateway Environment Configuration ---

# The Kubernetes Namespace where the Gateway will be installed
NAMESPACE=db-oracle

# The name of the secret for the Customer Fragment
CUSTOMER_FRAGMENT_SECRET_NAME=customer-fragment

# The filename of your customer fragment JSON
FRAGMENT_FILE=customer_fragments.json

# The name of the secret for Gateway Access Key
ACCESS_KEY_SECRET_NAME=access-key

# Helm release name for the Gateway
RELEASE_NAME=unified-gw