ADMIN_AUTH_METHOD_NAME=/Admin/admin-api-key
ADMIN_ACCESS_ID=p-qtlq7vbvnbzaam
ADMIN_ACCESS_KEY=g+7f3HDa5+x0z963D/AXD2XwSR9HoAsLePTW2juEyjk=

GATEWAY_AUTH_METHOD_NAME=/Gateway/gateway-api-key
GATEWAY_ACCESS_ID=p-yvhdwwutd9ooam
GATEWAY_ACCESS_KEY=T9g3/MP9iTZjfhv5jrIt+asdDNEcM8MNiPKihE4na+4=
